# Generated by Django 3.1.5 on 2021-03-31 19:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('body', models.TextField(verbose_name='message')),
                ('reading', models.BooleanField(default=False, verbose_name='it_reading')),
                ('from_user', models.ManyToManyField(related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ManyToManyField(related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Личное сообщение',
                'verbose_name_plural': 'Личные сообщения',
            },
        ),
    ]
