# Generated by Django 3.1.5 on 2021-03-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210327_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='changed',
            field=models.BooleanField(default=False),
        ),
    ]
